[build]
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment variables (configure in Netlify dashboard)
# EMAIL_USER = your-email@gmail.com
# EMAIL_PASS = your-app-password
# SITE_URL = https://your-site.netlify.app